### ISSUE TITLE
Receiving Exception when running model generated

### ISSUE THREAD

**Issue by alastor09** [curiousily/TensorFlow-on-Android-for-Human-Activity-Recognition-with-LSTMs#6]
When i am running the python file in Google Colab. and generate frozen_har.pb file
I am receiving below exception.
If you can help me in resolving the issue.

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.introml.activityrecognition, PID: 23391
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.introml.activityrecognition/io.github.introml.activityrecognition.MainActivity}: org.tensorflow.TensorFlowException: Op type not registered 'AddV2'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: org.tensorflow.TensorFlowException: Op type not registered 'AddV2'
        at org.tensorflow.Graph.importGraphDef(Native Method)
        at org.tensorflow.Graph.importGraphDef(Graph.java:118)
        at org.tensorflow.Graph.importGraphDef(Graph.java:102)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:390)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
        at io.github.introml.activityrecognition.TensorFlowClassifier.<init>(TensorFlowClassifier.java:23)
        at io.github.introml.activityrecognition.MainActivity.onCreate(MainActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) ```

**Comment by edgar-explorer** [comment]
@alastor09  Hi, have you solved this problem, I also received this problem.
E/vityrecognitio: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.introml.activityrecognition, PID: 25281
    java.lang.IllegalArgumentException: No Operation named [inputs] in the Graph
        at org.tensorflow.Session$Runner.operationByName(Session.java:343)
        at org.tensorflow.Session$Runner.feed(Session.java:137)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:407)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.feed(TensorFlowInferenceInterface.java:215)
        at io.github.introml.activityrecognition.TensorFlowClassifier.predictProbabilities(TensorFlowClassifier.java:34)
        at io.github.introml.activityrecognition.MainActivity.activityPrediction(MainActivity.java:113)
        at io.github.introml.activityrecognition.MainActivity.onSensorChanged(MainActivity.java:95)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:862)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Is different Tensorflow version?

**Comment by ouyangjunfei** [comment]
@cumtchenchang The author defines `input` as name In [Building the model](https://www.curiousily.com/posts/human-activity-recognition-using-lstms-on-android/#building-the-model). BUT you used **inputs**
